### ISSUE TITLE
No fire on the log

### ISSUE THREAD

**Issue by VikingScientist** [Duroktar/YuleLog#1]
Installed through pip, running python 3.5.2 on Ubuntu 16.04. Fire effect won't show. Snow works and both the text and log is displayed correctly, but no cozy warm fire :(

**Comment by VikingScientist** [comment]
![yulelog](https://user-images.githubusercontent.com/3500376/33986999-afc03c38-e0bf-11e7-8fb8-df66fd199b4d.png)

**Comment by Duroktar** [comment]
Seems not to be working for me either :( I'll have to dig in and see if I can't figure out what's causing the problem. Stay tuned ...

Ps. Sorry I didn't see this sooner! But thanks for checking it out, and Merry Christmas!

**Comment by Duroktar** [comment]
All fixed 🎁 

Merry Christmas 🎄
